# Setup
title:               Nate's Project Portfolio
description:         'This website functions as a way to document how I have explored or discovered interesting projects, ideas, and concepts in each of my core interests. Feel free to navigate through each page!'
url:                 ''
baseurl:             'ACosmicTardigrade.github.io/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Nate Denlinger             
  email:             natus2liamg@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
