# Setup
title:               Nate's Project Portfolio
url:                 ''
baseurl:             'ACosmicTardigrade.github.io/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Nate Denlinger             
  email:             natus2liamg@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
